---
minimum_pre_commit_version: "2.17"
default_stages: [pre-commit]
default_language_version:
  python: python3.10

ci:
  skip: [mypy, pylint, python-safety-dependencies-check, flakeheaven]

repos:
  # ----------------------------------------------
  # Meta hooks
  # ----------------------------------------------

  - repo: meta
    hooks:
      - id: identity
        stages: [pre-commit, manual]
      - id: check-hooks-apply
        stages: [manual]
      - id: check-useless-excludes
        stages: [manual]

  # ----------------------------------------------
  # File hooks
  # ----------------------------------------------

  # file checking out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable

  # ----------------------------------------------
  # Dependency hooks
  # ----------------------------------------------

  # safety - python dependency vulnerability checker
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: 3f01891d76160f03e9134ef025fb1eb1d10c85a2 # frozen: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
        args: ["--disable-optional-telemetry", "--full-report", "--ignore=51457"]
        files: pyproject.toml
        exclude: testing

  # ####################################################################################
  #
  #       FORMATTING
  #
  # ####################################################################################

  # ----------------------------------------------
  # Python
  # ----------------------------------------------

  # pyupgrade - upgrade old syntax to new
  - repo: https://github.com/asottile/pyupgrade
    rev: 19364aa1b2ac289ce75e6bbe93994f7b4b9425f6 # frozen: v3.19.0
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]

  # isort - sort imports
  - repo: https://github.com/PyCQA/isort
    rev: c235f5e450b4b84e58d114ed4c589cbf454175a3 # frozen: 5.13.2
    hooks:
      - id: isort

  # black - python formatter
  - repo: https://github.com/psf/black
    rev: 1b2427a2b785cc4aac97c19bb4b9a0de063f9547 # frozen: 24.10.0
    hooks:
      - id: black
        args: ["--safe"]

  # blacken-docs - black for python code in docs (rst/md/tex)
  - repo: https://github.com/asottile/blacken-docs
    rev: 78a9dcbecf4f755f65d1f3dec556bc249d723600 # frozen: 1.19.1
    hooks:
      - id: blacken-docs
        exclude: testing|tests

  # ----------------------------------------------
  # JS / TS / HTML / CSS / MD / JSON / YAML
  # ----------------------------------------------

  # prettier - multi formatter
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier

  # ----------------------------------------------
  # Spelling dict
  # ----------------------------------------------

  # Custom hook as python command
  - repo: local
    hooks:
      - id: sort-spelling-dicts
        name: Sort spelling_dict.txt files
        description: Sort spelling_dict.txt files
        language: python
        entry: python
        args:
          - "-c"
          - |
            import pathlib;
            import sys;
            p = pathlib.Path(sys.argv[1]);
            p.write_text("\n".join(sorted(set(p.read_text("utf-8").splitlines()))) + "\n", "utf-8")
        files: "spelling_dict.txt"

  # ----------------------------------------------
  # General (code unspecific)
  # ----------------------------------------------

  # code unspecific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]

  # ####################################################################################
  #
  #       LINTING
  #
  # ####################################################################################

  # ----------------------------------------------
  # General (code unspecific)
  # ----------------------------------------------

  - repo: local
    hooks:
      # Find TODO:|FIXME:|BUG: comments in all files
      # Inline skip: `#i#` directly after the colon after the tag-word
      - id: find-todos
        name: "Find TODO:|FIXME:|BUG: comments"
        description: "Check for TODO:|FIXME:|BUG: comments in all files"
        language: pygrep
        entry: '(^|//!?|#|<!--|;|/\*(\*|!)?|\.\.)\s*(TODO:|FIXME:|BUG:)(?!#i#)'
        exclude: TODO

  # code unspecific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key

  # ----------------------------------------------
  # Python
  # ----------------------------------------------

  # python specific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: name-tests-test
        args: ["--django"]

  # several python code regex hooks
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316 # frozen: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn

  # flakeheaven - wrapper for flake8
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: "289c489c9654342dae2ad871527c5951acb2f22d" # frozen: 3.3.0
    hooks:
      - id: flakeheaven
        types: [python]
        additional_dependencies:
          - "git+https://github.com/cielquan/my-flake8-plugins.git@v1.3.1"

  # Lint hooks managed via tox envs b/c they need the pkg installed
  - repo: local
    hooks:
      # mypy - python type checker
      - id: mypy
        name: mypy
        description: run mypy over the installed package via tox
        entry: tox
        args: ["-e", "mypy"]
        language: python
        additional_dependencies: [tox]
        types: [python]
        pass_filenames: false
        require_serial: true
        # pylint - python linter
      - id: pylint
        name: pylint
        description: run pylint over the installed package via tox
        entry: tox
        args: ["-e", "pylint", "--"]
        language: python
        additional_dependencies: [tox]
        types: [python]
        require_serial: true

  # pylint - python linter
  - repo: https://github.com/PyCQA/pylint/
    rev: a5a1bc3a9602d08f15ac90ad12f5b25bde375613 # frozen: v3.3.2
    hooks:
      - id: pylint
        name: spell-check (pylint+pyenchant)
        description: >
          spell-check in docstrings/comments in py-source via pyenchant and pylint
        args: ["--disable=all", "--enable=spelling", "--spelling-dict=en_US"]
        additional_dependencies: [pyenchant]
        exclude: "^(?!src).*"

  # poetry - python dependency management
  - repo: https://github.com/Cielquan/mirrors-poetry
    rev: a0effc6f95b7b6e0a7945be3701c832eb29c0fba # frozen: 1.8.5
    hooks:
      - id: poetry-check

  # ----------------------------------------------
  # Shell script
  # ----------------------------------------------

  # shellscript (via PyPI package)
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a23f6b85d0fdd5bb9d564e2579e678033debbdff # frozen: v0.10.0.1
    hooks:
      - id: shellcheck

  # ----------------------------------------------
  # Markdown
  # ----------------------------------------------

  # markdownlint - md file checker
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 1d349044b9624661f5a0a7e13e0ca9801752022a # frozen: v0.16.0
    hooks:
      - id: markdownlint-cli2

  # ----------------------------------------------
  # TOML / YAML
  # ----------------------------------------------

  # JSON specific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml

  # yamllint - yaml linter
  - repo: https://github.com/adrienverge/yamllint
    rev: 81e9f98ffd059efe8aa9c1b1a42e5cce61b640c6 # frozen: v1.35.1
    hooks:
      - id: yamllint
